TEMPLATEROOT = ../

# compilation flags for gdb                                                     

CFLAGS  = -O1 -g
ASFLAGS = -g

# object files                                                                  

OBJS=  $(STARTUP) main.o game.o game_view.o tile.o tiles.o player.o game_player.o monster.o monsters.o bullet.o bullets.o common_defs.o newlib_stubs.o f3d_delay.o f3d_lcd_sd.o f3d_user_btn.o glcdfont.o f3d_uart.o f3d_gyro.o f3d_accel.o f3d_nunchuk.o f3d_i2c.o stm32f30x_spi.o stm32f30x_tim.o stm32f30x_rcc.o stm32f30x_gpio.o stm32f30x_usart.o stm32f30x_i2c.o

# include common make file                                                      

include $(TEMPLATEROOT)/makefile_root.mk

